# Generated by Django 3.0.5 on 2020-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200416_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
