# Generated by Django 3.0.5 on 2020-04-15 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut_name', models.CharField(max_length=150, verbose_name='Fullname')),
                ('aut_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('aut_status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Active')], verbose_name='Status')),
                ('aut_created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('aut_modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification Date')),
                ('aut_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autors',
            },
        ),
    ]
